// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HDlzhRDt_00scX6xMVN2E15kR2Jaeac',
    appId: '1:804324321291:web:d46d91ec12894e9647bf0e',
    messagingSenderId: '804324321291',
    projectId: 'blogapp-dd5b0',
    authDomain: 'blogapp-dd5b0.firebaseapp.com',
    storageBucket: 'blogapp-dd5b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHp8SNu11x_vrmbmBw-2OCWV-FDBYnvno',
    appId: '1:804324321291:android:9426205efb59ac1547bf0e',
    messagingSenderId: '804324321291',
    projectId: 'blogapp-dd5b0',
    storageBucket: 'blogapp-dd5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsWsf6uEw9iaUCr0TmDSDMA0O4zcjB80',
    appId: '1:804324321291:ios:356a30772e93b47747bf0e',
    messagingSenderId: '804324321291',
    projectId: 'blogapp-dd5b0',
    storageBucket: 'blogapp-dd5b0.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );
}
